grbfrc-0.1: grbfrc::Gloverizer Class Reference
grbfrc::Gloverizer Class Reference
#include <Gloverizer.hpp>
Public Member Functions
Gloverizer (GRBModel *xmodel, GRBVar *xu, double umax)
void gloverize ()
Private Member Functions
void add_glover_variables ()
void linearize_qconstr (GRBQConstr *qconstr)
void linearize_objective ()
Private Attributes
GRBModel * model
GRBVar * u
double U
std::map< GRBVar *, GRBVar > glvrvr
Detailed Description
Definition at line 46 of file Gloverizer.hpp.
Constructor & Destructor Documentation
Gloverizer()
grbfrc::Gloverizer::Gloverizer (GRBModel * xmodel, GRBVar * xu, double umax)
Definition at line 8 of file Gloverizer.cpp.
References u, and U.
                        : model { xmodel },
                          u { xu },
                          U { umax } { }
Member Function Documentation
add_glover_variables()
void grbfrc::Gloverizer::add_glover_variables () private
Definition at line 25 of file Gloverizer.cpp.
References glvrvr, model, u, and U.
Referenced by gloverize().
{
     std::cout << "Adding Glover variables ..." << std::endl;
     GRBVar* var { model->getVars() };
     double L { u->get(GRB_DoubleAttr_LB) };
     int numVars { model->get(GRB_IntAttr_NumVars) };
     for (int i = 0; i < numVars; i++) {
         if (var->get(GRB_CharAttr_VType) != 'C')
             glvrvr[var] = model->addVar(-GRB_INFINITY, GRB_INFINITY, 0.0, 'C');
         var++;
     }
     model->update();
     for (auto& var2glvrvar: glvrvr) {
         model->addConstr( var2glvrvar.second <= U*(*var2glvrvar.first) );
         model->addConstr( var2glvrvar.second >= L*(*var2glvrvar.first) );
         model->addConstr( *u - U*(1 - (*var2glvrvar.first)) <= var2glvrvar.second );
         model->addConstr( *u - L*(1 - (*var2glvrvar.first)) >= var2glvrvar.second );
     }
 }
gloverize()
void grbfrc::Gloverizer::gloverize ()
Definition at line 13 of file Gloverizer.cpp.
References add_glover_variables(), linearize_objective(), linearize_qconstr(), and model.
Referenced by grbfrc::YGGY::do_the_rest().
{
     add_glover_variables();
     std::cout << "Linearizing quadratic constraints and objective..." << std::endl;
     GRBQConstr* qconstr { model->getQConstrs() };
     for (int q = 0; q < model->get(GRB_IntAttr_NumQConstrs); q++) {
         linearize_qconstr(qconstr);
         qconstr++;
     }
     linearize_objective();
     model->update();
 }
linearize_objective()
void grbfrc::Gloverizer::linearize_objective () private
Definition at line 66 of file Gloverizer.cpp.
References glvrvr, and model.
Referenced by gloverize().
{
     GRBQuadExpr oldobj { model->getObjective() };
     GRBLinExpr newobj { oldobj.getLinExpr() };
     GRBVar* binvar { nullptr };
     for (unsigned int i = 0; i < oldobj.size(); i++) {
         GRBVar var1 { oldobj.getVar1(i) };
         GRBVar var2 { oldobj.getVar2(i) };
         if (var1.get(GRB_CharAttr_VType) != 'C')
             binvar = &var1;
         else
             binvar = &var2;
         for (auto& var2glvrvr: glvrvr)
             if (binvar->sameAs(*var2glvrvr.first))
                 newobj += oldobj.getCoeff(i) * var2glvrvr.second;
     }
     model->setObjective(newobj, model->get(GRB_IntAttr_ModelSense));
 }
linearize_qconstr()
void grbfrc::Gloverizer::linearize_qconstr (GRBQConstr * qconstr) private
Definition at line 44 of file Gloverizer.cpp.
References glvrvr, and model.
Referenced by gloverize().
{
     GRBQConstr* qc { qconstr };
     GRBQuadExpr qexpr { model->getQCRow(*qc) };
     GRBLinExpr new_lhs { qexpr.getLinExpr() };
     GRBVar* binvar { nullptr };
     for (unsigned int i = 0; i < qexpr.size(); i++) {
         GRBVar var1 { qexpr.getVar1(i) };
         GRBVar var2 { qexpr.getVar2(i) };
         if (var1.get(GRB_CharAttr_VType) != 'C')
             binvar = &var1;
         else
             binvar = &var2;
         for (auto& var2glvrvr: glvrvr)
             if (binvar->sameAs(*var2glvrvr.first))
                 new_lhs += qexpr.getCoeff(i) * var2glvrvr.second;
     }
     model->addConstr(new_lhs,
                      qc->get(GRB_CharAttr_QCSense),
                      qc->get(GRB_DoubleAttr_QCRHS));
     model->remove(*qc);
 }
Member Data Documentation
glvrvr
std::map<GRBVar*, GRBVar> grbfrc::Gloverizer::glvrvr private
Definition at line 53 of file Gloverizer.hpp.
Referenced by add_glover_variables(), linearize_objective(), and linearize_qconstr().
model
GRBModel* grbfrc::Gloverizer::model private
Definition at line 50 of file Gloverizer.hpp.
Referenced by add_glover_variables(), gloverize(), linearize_objective(), and linearize_qconstr().
u
GRBVar* grbfrc::Gloverizer::u private
Definition at line 51 of file Gloverizer.hpp.
Referenced by add_glover_variables(), and Gloverizer().
U
double grbfrc::Gloverizer::U private
Definition at line 52 of file Gloverizer.hpp.
Referenced by add_glover_variables(), and Gloverizer().
The documentation for this class was generated from the following files:
/datadisk/bbubu/projects/libgrbfrc/src/Gloverizer.hpp
/datadisk/bbubu/projects/libgrbfrc/src/Gloverizer.cpp