grbfrc-0.1: grbfrc::GrbfrcCallback< T > Class Template Reference
grbfrc::GrbfrcCallback< T > Class Template Reference
#include <GrbfrcCallback.hpp>
Public Member Functions
GrbfrcCallback (Callback< T > *xcb, std::vector< std::map< T, GRBVar >> *xvargrps=nullptr)
GRBCallback * yield (std::vector< GRBVar *> &tx, std::vector< GRBVar *> *vars)
GRBCallback * yield ()
Private Attributes
std::vector< std::map< T, GRBVar > > * vargrps
Callback< T > * cb
Detailed Description
template<typename T>
class grbfrc::GrbfrcCallback< T >
Definition at line 101 of file GrbfrcCallback.hpp.
Constructor & Destructor Documentation
GrbfrcCallback()
template<typename T> grbfrc::GrbfrcCallback< T >::GrbfrcCallback (Callback< T > * xcb, std::vector< std::map< T, GRBVar >> * xvargrps = nullptr) inline
Definition at line 110 of file GrbfrcCallback.hpp.
         : vargrps { xvargrps }, cb { xcb } { }
Member Function Documentation
yield() [1/2]
template<typename T> GRBCallback* grbfrc::GrbfrcCallback< T >::yield (std::vector< GRBVar *> & tx, std::vector< GRBVar *> * vars) inline
Definition at line 114 of file GrbfrcCallback.hpp.
References grbfrc::Callback< T >::yield().
Referenced by grbfrc::CharnesCooper::run(), grbfrc::ObjVarTransform::transform(), and grbfrc::YGGY::transform().
{
         return cb->yield(tx, vars, vargrps);
     }
yield() [2/2]
template<typename T> GRBCallback* grbfrc::GrbfrcCallback< T >::yield () inline
Definition at line 119 of file GrbfrcCallback.hpp.
References grbfrc::Callback< T >::yield().
{
         return cb->yield(vargrps);
     }
Member Data Documentation
cb
template<typename T> Callback<T>* grbfrc::GrbfrcCallback< T >::cb private
Definition at line 106 of file GrbfrcCallback.hpp.
vargrps
template<typename T> std::vector<std::map<T,GRBVar> >* grbfrc::GrbfrcCallback< T >::vargrps private
Definition at line 105 of file GrbfrcCallback.hpp.
The documentation for this class was generated from the following file:
/datadisk/bbubu/projects/libgrbfrc/src/GrbfrcCallback.hpp