grbfrc-0.1: grbfrc::Callback< T > Class Template Reference
grbfrc::Callback< T > Class Template Reference
#include <GrbfrcCallback.hpp>
Public Member Functions
GRBCallback * yield (std::vector< GRBVar *> &tx, std::vector< GRBVar *> *vars, std::vector< std::map< T, GRBVar >> *vargrps=nullptr)
GRBCallback * yield (std::vector< std::map< T, GRBVar >> *vargrps=nullptr)
virtual void register_vargrps ()
GRBCallback * init_callback ()
Protected Attributes
GRBCallback * cbp { nullptr }
std::vector< std::map< T, GRBVar > > * transformed_vargrps { nullptr }
Private Member Functions
int getIndex (GRBVar &var, std::vector< GRBVar *> *vars)
Detailed Description
template<typename T>
class grbfrc::Callback< T >
Definition at line 47 of file GrbfrcCallback.hpp.
Member Function Documentation
getIndex()
template<typename T> int grbfrc::Callback< T >::getIndex (GRBVar & var, std::vector< GRBVar *> * vars) inline private
Definition at line 92 of file GrbfrcCallback.hpp.
Referenced by grbfrc::Callback< T >::yield().
{
         for (unsigned int i = 0; i < vars->size(); i++)
             if (var.sameAs(*((*vars)[i]))) return i;
         return -1;
     }
init_callback()
template<typename T> GRBCallback* grbfrc::Callback< T >::init_callback () inline
Definition at line 81 of file GrbfrcCallback.hpp.
References grbfrc::Callback< T >::cbp.
Referenced by grbfrc::Callback< T >::yield().
{
         return this->cbp;
     }
register_vargrps()
template<typename T> virtual void grbfrc::Callback< T >::register_vargrps () inline virtual
Definition at line 77 of file GrbfrcCallback.hpp.
Referenced by grbfrc::Callback< T >::yield().
{
     }
yield() [1/2]
template<typename T> GRBCallback* grbfrc::Callback< T >::yield (std::vector< GRBVar *> & tx, std::vector< GRBVar *> * vars, std::vector< std::map< T, GRBVar >> * vargrps = nullptr) inline
Definition at line 51 of file GrbfrcCallback.hpp.
References grbfrc::Callback< T >::getIndex(), grbfrc::Callback< T >::init_callback(), grbfrc::Callback< T >::register_vargrps(), and grbfrc::Callback< T >::transformed_vargrps.
Referenced by grbfrc::GrbfrcCallback< T >::yield().
{
         // check whether referenced variables are discrete
         if (vargrps) {
             transformed_vargrps = new std::vector<std::map<T, GRBVar>>();
             for (std::map<T, GRBVar>& vargrp : *(vargrps)) {
                 std::map<T, GRBVar> transformed_vargrp;
                 for (auto& e: vargrp)
                     transformed_vargrp[e.first] = *tx[getIndex(e.second, vars)];
                 transformed_vargrps->push_back(transformed_vargrp);
             }
             this->register_vargrps();
         }
         return init_callback();
     }
yield() [2/2]
template<typename T> GRBCallback* grbfrc::Callback< T >::yield (std::vector< std::map< T, GRBVar >> * vargrps = nullptr) inline
Definition at line 68 of file GrbfrcCallback.hpp.
References grbfrc::Callback< T >::init_callback(), grbfrc::Callback< T >::register_vargrps(), and grbfrc::Callback< T >::transformed_vargrps.
{
         if (vargrps) {
             transformed_vargrps = new std::vector<std::map<T, GRBVar>>();
             *transformed_vargrps = *vargrps;
             this->register_vargrps();
         }
         return init_callback();
     }
Member Data Documentation
cbp
template<typename T> GRBCallback* grbfrc::Callback< T >::cbp { nullptr } protected
Definition at line 87 of file GrbfrcCallback.hpp.
Referenced by grbfrc::Callback< T >::init_callback().
transformed_vargrps
template<typename T> std::vector<std::map<T,GRBVar> >* grbfrc::Callback< T >::transformed_vargrps { nullptr } protected
Definition at line 88 of file GrbfrcCallback.hpp.
Referenced by grbfrc::Callback< T >::yield().
The documentation for this class was generated from the following file:
/datadisk/bbubu/projects/libgrbfrc/src/GrbfrcCallback.hpp