grbfrc-0.1: grbfrc::Solver Class Reference
grbfrc::Solver Class Reference
#include <Solver.hpp>
Public Member Functions
Solver (GRBModel *base_model_ptr, FMILPObj *objptr, std::vector< GRBVar *> *varsptr, std::vector< double > *startptr, FMILPSol **solptr)
template<typename T >
void solve (Algorithm algorithm=Algorithm::GCC, GrbfrcCallback< T > *cb=nullptr, double *objub=nullptr, double *objlb=nullptr)
template<typename T >
void _solve (CharnesCooper *algorithm, GrbfrcCallback< T > *cb=nullptr)
template<typename T >
void _solve (Dinkelbach *algorithm, GrbfrcCallback< T > *cb=nullptr)
template<typename T >
void _solve (YGGY *algorithm, GrbfrcCallback< T > *cb=nullptr)
template<typename T >
void _solve (ObjVarTransform *algorithm, GrbfrcCallback< T > *cb=nullptr)
Private Attributes
GRBModel * base_model { nullptr }
FMILPObj * objective { nullptr }
std::vector< GRBVar * > * vars { nullptr }
std::vector< double > * start_solution { nullptr }
FMILPSol ** solution { nullptr }
Detailed Description
Definition at line 17 of file Solver.hpp.
Constructor & Destructor Documentation
Solver()
grbfrc::Solver::Solver (GRBModel * base_model_ptr, FMILPObj * objptr, std::vector< GRBVar *> * varsptr, std::vector< double > * startptr, FMILPSol ** solptr)
Definition at line 6 of file Solver.cpp.
References objective, solution, start_solution, and vars.
     : base_model { base_model_ptr },
       objective { objptr },
       vars { varsptr },
       start_solution { startptr },
       solution { solptr }
    { }
Member Function Documentation
_solve() [1/4]
template<typename T > void grbfrc::Solver::_solve (CharnesCooper * algorithm, GrbfrcCallback< T > * cb = nullptr)
Definition at line 83 of file Solver.hpp.
References base_model, grbfrc::_Algorithm::init(), objective, grbfrc::CharnesCooper::run(), solution, start_solution, vars, and grbfrc::CharnesCooper::writeSolution().
Referenced by solve().
{
     algorithm->init(base_model,
                     objective,
                     vars,
                     start_solution);
     algorithm->run(cb);
     // check for sanity ...
     // then:
     algorithm->writeSolution(solution);
 }
_solve() [2/4]
template<typename T > void grbfrc::Solver::_solve (Dinkelbach * algorithm, GrbfrcCallback< T > * cb = nullptr)
Definition at line 95 of file Solver.hpp.
References base_model, grbfrc::_Algorithm::init(), objective, grbfrc::Dinkelbach::run(), solution, start_solution, vars, and grbfrc::Dinkelbach::writeSolution().
{
     algorithm->init(base_model,
                     objective,
                     vars,
                     start_solution);
     algorithm->run(cb);
     // check for sanity ...
     // then:
     algorithm->writeSolution(solution);
 }
_solve() [3/4]
template<typename T > void grbfrc::Solver::_solve (YGGY * algorithm, GrbfrcCallback< T > * cb = nullptr)
Definition at line 107 of file Solver.hpp.
References base_model, grbfrc::_Algorithm::init(), objective, grbfrc::YGGY::run(), solution, start_solution, vars, and grbfrc::YGGY::writeSolution().
{
     algorithm->init(base_model,
                     objective,
                     vars,
                     start_solution);
     algorithm->run(cb);
     // check for sanity ...
     // then:
     algorithm->writeSolution(solution);
 }
_solve() [4/4]
template<typename T > void grbfrc::Solver::_solve (ObjVarTransform * algorithm, GrbfrcCallback< T > * cb = nullptr)
Definition at line 119 of file Solver.hpp.
References base_model, grbfrc::_Algorithm::init(), objective, grbfrc::ObjVarTransform::run(), solution, start_solution, vars, and grbfrc::ObjVarTransform::writeSolution().
{
     algorithm->init(base_model,
                     objective,
                     vars,
                     start_solution);
     algorithm->run(cb);
     // check for sanity ...
     // then:
     algorithm->writeSolution(solution);
 }
solve()
template<typename T > void grbfrc::Solver::solve (Algorithm algorithm = Algorithm::GCC, GrbfrcCallback< T > * cb = nullptr, double * objub = nullptr, double * objlb = nullptr)
Definition at line 60 of file Solver.hpp.
References _solve(), base_model, grbfrc::CCT, grbfrc::DTA, and grbfrc::OVT.
Referenced by grbfrc::FMILP::optimize(), and grbfrc::FMILP::runGeneralizedCharnesCooper().
{
     GRBEnv env = base_model->getEnv();
     if (algorithm == Algorithm::CCT) {
         CharnesCooper _algorithm = CharnesCooper(&env);
         this->_solve(&_algorithm, cb);
     }
     else if (algorithm == Algorithm::DTA) {
         Dinkelbach _algorithm = Dinkelbach();
         this->_solve(&_algorithm, cb);
     }
     else if (algorithm == Algorithm::OVT) {
         ObjVarTransform _algorithm = ObjVarTransform(&env, objub, objlb);
         this->_solve(&_algorithm, cb);
     }
     else {
         YGGY _algorithm = YGGY(&env);
         this->_solve(&_algorithm, cb);
     }
 }
Member Data Documentation
base_model
GRBModel* grbfrc::Solver::base_model { nullptr } private
Definition at line 21 of file Solver.hpp.
Referenced by _solve(), and solve().
objective
FMILPObj* grbfrc::Solver::objective { nullptr } private
Definition at line 22 of file Solver.hpp.
Referenced by _solve(), and Solver().
solution
FMILPSol** grbfrc::Solver::solution { nullptr } private
Definition at line 25 of file Solver.hpp.
Referenced by _solve(), and Solver().
start_solution
std::vector<double>* grbfrc::Solver::start_solution { nullptr } private
Definition at line 24 of file Solver.hpp.
Referenced by _solve(), and Solver().
vars
std::vector<GRBVar*>* grbfrc::Solver::vars { nullptr } private
Definition at line 23 of file Solver.hpp.
Referenced by _solve(), and Solver().
The documentation for this class was generated from the following files:
/datadisk/bbubu/projects/libgrbfrc/src/Solver.hpp
/datadisk/bbubu/projects/libgrbfrc/src/Solver.cpp