grbfrc-0.1: grbfrc::ObjVarTransform Class Reference
grbfrc::ObjVarTransform Class Reference
#include <ObjVarTransform.hpp>
Public Member Functions
ObjVarTransform (GRBEnv *env, double *objub=nullptr, double *objlb=nullptr)
void printInvalidity ()
template<typename T >
int transform (GrbfrcCallback< T > *cb)
GRBModel getTransform ()
void solveTransform ()
template<typename T >
void run (GrbfrcCallback< T > *cb)
void writeSolution (FMILPSol **xsolution)
Public Member Functions inherited from grbfrc::_Algorithm
void init (GRBModel *xbase_model, FMILPObj *xobjective, std::vector< GRBVar *> *xvars, std::vector< double > *xstart_solution)
Private Member Functions
void copy_model ()
void backTransformSolution ()
int getIndex (GRBVar &var)
void add_u_constraint ()
Private Attributes
FMILPSol solution
bool invalid
bool transformed
GRBModel transformation
GRBVar u
std::vector< GRBVar * > tx
double * umax
double * umin
Additional Inherited Members
Protected Attributes inherited from grbfrc::_Algorithm
GRBModel * base_model
FMILPObj * objective
std::vector< GRBVar * > * vars
std::vector< double > * start_solution
GRBCallback * callback
Detailed Description
Definition at line 92 of file ObjVarTransform.hpp.
Constructor & Destructor Documentation
ObjVarTransform()
grbfrc::ObjVarTransform::ObjVarTransform (GRBEnv * env, double * objub = nullptr, double * objlb = nullptr)
Definition at line 7 of file ObjVarTransform.cpp.
References transformation, transformed, umax, and umin.
                                  : invalid { false },
                                    transformed { false },
                                    transformation { GRBModel(*env) },
                                    umax { objub },
                                    umin { objlb } { }
Member Function Documentation
add_u_constraint()
void grbfrc::ObjVarTransform::add_u_constraint () private
Definition at line 49 of file ObjVarTransform.cpp.
References grbfrc::FMILPObj::denominator, getIndex(), grbfrc::FMILPObj::numerator, grbfrc::_Algorithm::objective, transformation, tx, u, umax, and umin.
Referenced by run(), and transform().
{
     const GRBLinExpr& objnum { objective->numerator };
     GRBLinExpr transformed_objnum { objnum.getConstant() };
     for (unsigned int i = 0; i < objnum.size(); ++i) {
         GRBVar var = objnum.getVar(i);
         transformed_objnum += objnum.getCoeff(i) * (*tx[getIndex(var)]);
     }
     const GRBLinExpr& objdenom { objective->denominator };
     GRBLinExpr transformed_objdenom { objdenom.getConstant() };
     for (unsigned int i = 0; i < objdenom.size(); ++i) {
         GRBVar glover_var = transformation.addVar(-GRB_INFINITY, GRB_INFINITY, 0.0, 'C');
         transformation.update();
         GRBVar var = objdenom.getVar(i);
         GRBVar* varp = tx[getIndex(var)];
         double U = *umax;
         double L = *umin;
         transformation.addConstr( glover_var <= U*(*varp) );
         transformation.addConstr( glover_var >= L*(*varp) );
         transformation.addConstr( u - U*(1 - (*varp)) <= glover_var );
         transformation.addConstr( u - L*(1 - (*varp)) >= glover_var );
         transformed_objdenom += objdenom.getCoeff(i) * glover_var;
     }
     transformation.addConstr(transformed_objdenom <= transformed_objnum);
 }
backTransformSolution()
void grbfrc::ObjVarTransform::backTransformSolution () private
Definition at line 106 of file ObjVarTransform.cpp.
References grbfrc::_Algorithm::base_model, grbfrc::FMILPSol::objVal, solution, transformation, tx, and grbfrc::FMILPSol::varVals.
Referenced by run().
{
     int status { transformation.get(GRB_IntAttr_Status) };
     if (status == GRB_OPTIMAL) {
       solution.objVal = transformation.get(GRB_DoubleAttr_ObjVal);
       for (int i = 0; i < base_model->get(GRB_IntAttr_NumVars); i++)
           solution.varVals.push_back( tx[i]->get(GRB_DoubleAttr_X) );
     }
     else std::cout << "GRB_Status : " << transformation.get(GRB_IntAttr_Status) << std::endl;
 }
copy_model()
void grbfrc::ObjVarTransform::copy_model () private
Definition at line 21 of file ObjVarTransform.cpp.
References grbfrc::_Algorithm::base_model, getIndex(), transformation, tx, and grbfrc::_Algorithm::vars.
Referenced by run(), and transform().
{
     for (int i = 0; i < base_model->get(GRB_IntAttr_NumVars); ++i) {
         GRBVar* varp = vars->operator[](i);
         tx.push_back(new GRBVar( transformation.addVar(varp->get(GRB_DoubleAttr_LB),
                                                        varp->get(GRB_DoubleAttr_UB),
                                                        0.0,
                                                        varp->get(GRB_CharAttr_VType)) ));
     }
     GRBConstr* constrs { base_model->getConstrs() };
     int numConstrs { base_model->get(GRB_IntAttr_NumConstrs) };
     for (int k = 0; k < numConstrs; k++) {
       GRBLinExpr origLhs { base_model->getRow(*constrs) };
       double b { constrs->get(GRB_DoubleAttr_RHS) };
       GRBLinExpr lhs = -b;
       for (unsigned int i = 0; i < origLhs.size(); i++) {
         GRBVar var = origLhs.getVar(i);
         int j = getIndex(var);
         double coeff = origLhs.getCoeff(i);
         lhs += coeff * ( *tx[j] );
        }
       char constrSense { constrs->get(GRB_CharAttr_Sense) };
       transformation.addConstr(lhs, constrSense, 0.0);
       constrs++;
      }
 }
getIndex()
int grbfrc::ObjVarTransform::getIndex (GRBVar & var) private
Definition at line 122 of file ObjVarTransform.cpp.
References grbfrc::_Algorithm::base_model, and grbfrc::_Algorithm::vars.
Referenced by add_u_constraint(), copy_model(), and run().
{
     for (int i = 0; i < base_model->get(GRB_IntAttr_NumVars); i++)
         if (var.sameAs(*((*vars)[i]))) return i;
     return -1;
 }
getTransform()
GRBModel grbfrc::ObjVarTransform::getTransform ()
Definition at line 76 of file ObjVarTransform.cpp.
References invalid, printInvalidity(), transformation, and transformed.
Referenced by transform().
{
     if (invalid) {
         printInvalidity();
         return transformation;
     }
     else if (transformed)
         return transformation;
     else {
         //transform();
         return transformation;
     }
 }
printInvalidity()
void grbfrc::ObjVarTransform::printInvalidity ()
Definition at line 15 of file ObjVarTransform.cpp.
Referenced by getTransform(), run(), and solveTransform().
{
    // if (no umax available) "no umax"
    // if (no umin available) "no umin"
    // else if (continuous vars in denominator) "continuous variables in denominator"
 }
run()
template<typename T > void grbfrc::ObjVarTransform::run (GrbfrcCallback< T > * cb) inline
Definition at line 133 of file ObjVarTransform.hpp.
References add_u_constraint(), backTransformSolution(), copy_model(), getIndex(), printInvalidity(), solveTransform(), transform(), and writeSolution().
Referenced by grbfrc::Solver::_solve().
{
             if (invalid)
                 printInvalidity();
             else {
                 std::cout << "\n=========== solving FMIP via Objective Variable Transform transform ===========\n\n";
                 if (!transformed) transform(cb);
                 solveTransform();
                 backTransformSolution();
             }
         }
solveTransform()
void grbfrc::ObjVarTransform::solveTransform ()
Definition at line 89 of file ObjVarTransform.cpp.
References invalid, printInvalidity(), and transformation.
Referenced by run(), and transform().
{
     if (invalid)
         printInvalidity();
     else {
         try {
             transformation.optimize();
             std::cout << std::endl;
         }
         catch (GRBException e) {
             std::cout << "Gurobi error: " << e.getMessage() << "\n\n";
         }
         catch (...) {
             std::cout << "Error while attempting to optimize transform ... \n\n";
         }
     }
 }
transform()
template<typename T > int grbfrc::ObjVarTransform::transform (GrbfrcCallback< T > * cb) inline
Definition at line 111 of file ObjVarTransform.hpp.
References add_u_constraint(), grbfrc::_Algorithm::base_model, grbfrc::_Algorithm::callback, copy_model(), getTransform(), solveTransform(), grbfrc::_Algorithm::vars, and grbfrc::GrbfrcCallback< T >::yield().
Referenced by run().
{
             copy_model();
             u = transformation.addVar(*umin, *umax, 0.0, GRB_CONTINUOUS);
             transformation.setObjective(GRBLinExpr(u), base_model->get(GRB_IntAttr_ModelSense));
             transformation.update();
             add_u_constraint();
             if (cb) {
                 callback = cb->yield(tx, vars);
                 transformation.setCallback(callback);
             }
             transformation.update();
             return 0;
         }
writeSolution()
void grbfrc::ObjVarTransform::writeSolution (FMILPSol ** xsolution) virtual
Implements grbfrc::_Algorithm.
Definition at line 116 of file ObjVarTransform.cpp.
References solution.
Referenced by grbfrc::Solver::_solve(), and run().
{
     if (*xsolution) **xsolution = solution;
     else if (!*xsolution) *xsolution = new FMILPSol(solution);
     else std::cout << "No solution avaiable!" << std::endl;
 }
Member Data Documentation
invalid
bool grbfrc::ObjVarTransform::invalid private
Definition at line 97 of file ObjVarTransform.hpp.
Referenced by getTransform(), and solveTransform().
solution
FMILPSol grbfrc::ObjVarTransform::solution private
Definition at line 96 of file ObjVarTransform.hpp.
Referenced by backTransformSolution(), and writeSolution().
transformation
GRBModel grbfrc::ObjVarTransform::transformation private
Definition at line 99 of file ObjVarTransform.hpp.
Referenced by add_u_constraint(), backTransformSolution(), copy_model(), getTransform(), ObjVarTransform(), and solveTransform().
transformed
bool grbfrc::ObjVarTransform::transformed private
Definition at line 98 of file ObjVarTransform.hpp.
Referenced by getTransform(), and ObjVarTransform().
tx
std::vector<GRBVar*> grbfrc::ObjVarTransform::tx private
Definition at line 101 of file ObjVarTransform.hpp.
Referenced by add_u_constraint(), backTransformSolution(), and copy_model().
u
GRBVar grbfrc::ObjVarTransform::u private
Definition at line 100 of file ObjVarTransform.hpp.
Referenced by add_u_constraint().
umax
double* grbfrc::ObjVarTransform::umax private
Definition at line 102 of file ObjVarTransform.hpp.
Referenced by add_u_constraint(), and ObjVarTransform().
umin
double* grbfrc::ObjVarTransform::umin private
Definition at line 103 of file ObjVarTransform.hpp.
Referenced by add_u_constraint(), and ObjVarTransform().
The documentation for this class was generated from the following files:
/datadisk/bbubu/projects/libgrbfrc/src/ObjVarTransform.hpp
/datadisk/bbubu/projects/libgrbfrc/src/ObjVarTransform.cpp