grbfrc-0.1: grbfrc::CharnesCooper Class Reference
grbfrc::CharnesCooper Class Reference
#include <CharnesCooper.hpp>
Public Member Functions
CharnesCooper (GRBEnv *env)
void printInvalidity ()
void transform ()
GRBModel getTransform ()
void solveTransform ()
void solveTransform (GRBCallback &callback)
template<typename T >
void run (GrbfrcCallback< T > *cb)
virtual void writeSolution (FMILPSol **xsolution) override
FMILPSol getSolution ()
Public Member Functions inherited from grbfrc::_Algorithm
void init (GRBModel *xbase_model, FMILPObj *xobjective, std::vector< GRBVar *> *xvars, std::vector< double > *xstart_solution)
Private Member Functions
void backTransformSolution ()
int getIndex (GRBVar &var)
Private Attributes
FMILPSol solution
bool invalid
bool transformed
GRBModel transformation
GRBVar t
std::vector< GRBVar * > y
Additional Inherited Members
Protected Attributes inherited from grbfrc::_Algorithm
GRBModel * base_model
FMILPObj * objective
std::vector< GRBVar * > * vars
std::vector< double > * start_solution
GRBCallback * callback
Detailed Description
Definition at line 50 of file CharnesCooper.hpp.
Constructor & Destructor Documentation
CharnesCooper()
grbfrc::CharnesCooper::CharnesCooper (GRBEnv * env)
Definition at line 11 of file CharnesCooper.cpp.
References transformation.
              : transformed { false },
                transformation { GRBModel(*env) }
  {
   //if (!fmip->isFLP()) { printInvalidity(); invalid = true; }
   //else { invalid = false; base_model->update(); }
   // base_model->update();
  }
Member Function Documentation
backTransformSolution()
void grbfrc::CharnesCooper::backTransformSolution () private
Definition at line 136 of file CharnesCooper.cpp.
References grbfrc::_Algorithm::base_model, grbfrc::FMILPSol::objVal, solution, t, transformation, grbfrc::FMILPSol::varVals, and y.
Referenced by run().
  {
   int status { transformation.get(GRB_IntAttr_Status) };
   if (status == GRB_OPTIMAL)
    {
     solution.objVal = transformation.get(GRB_DoubleAttr_ObjVal);
     double tvalue { t.get(GRB_DoubleAttr_X) };
     for (int i = 0; i < base_model->get(GRB_IntAttr_NumVars); i++)
      {
       double value { y[i]->get(GRB_DoubleAttr_X) };
       solution.varVals.push_back( value / tvalue );
      }
    }
   else std::cout << "GRB_Status : " << transformation.get(GRB_IntAttr_Status) << std::endl;
  }
getIndex()
int grbfrc::CharnesCooper::getIndex (GRBVar & var) private
Definition at line 152 of file CharnesCooper.cpp.
References grbfrc::_Algorithm::base_model, and grbfrc::_Algorithm::vars.
Referenced by run(), and transform().
  {
   for (int i = 0; i < base_model->get(GRB_IntAttr_NumVars); i++)
     if (var.sameAs(*((*vars)[i]))) return i;
   return -1;
  }
getSolution()
FMILPSol grbfrc::CharnesCooper::getSolution ()
Definition at line 131 of file CharnesCooper.cpp.
References solution.
Referenced by run().
  {
   return solution;
  }
getTransform()
GRBModel grbfrc::CharnesCooper::getTransform ()
Definition at line 88 of file CharnesCooper.cpp.
References invalid, printInvalidity(), transform(), transformation, and transformed.
  {
   if (invalid)
    {
     printInvalidity();
     return transformation;
    }
   else if (transformed) return transformation;
   else
    {
     transform();
     return transformation;
    }
  }
printInvalidity()
void grbfrc::CharnesCooper::printInvalidity ()
Definition at line 20 of file CharnesCooper.cpp.
Referenced by getTransform(), run(), and solveTransform().
  {
    std::cout << "\n!!! === Not a FLP === !!!\n\n";
  }
run()
template<typename T > void grbfrc::CharnesCooper::run (GrbfrcCallback< T > * cb) inline
Definition at line 71 of file CharnesCooper.hpp.
References backTransformSolution(), grbfrc::_Algorithm::callback, getIndex(), getSolution(), printInvalidity(), solveTransform(), transform(), grbfrc::_Algorithm::vars, writeSolution(), and grbfrc::GrbfrcCallback< T >::yield().
Referenced by grbfrc::Solver::_solve().
{
         if (invalid) printInvalidity();
         else
          {
           std::cout << "\n=========== solving FLP via Charnes-Cooper transform ===========\n\n";
           if (!transformed) transform();
           if (cb) {
               callback = cb->yield(y, vars);
               transformation.setCallback(callback);
           }
           solveTransform();
           backTransformSolution();
          }
     }
solveTransform() [1/2]
void grbfrc::CharnesCooper::solveTransform ()
Definition at line 103 of file CharnesCooper.cpp.
References invalid, printInvalidity(), and transformation.
Referenced by run().
  {
   if (invalid) printInvalidity();
   else
    {
     try
      {
       transformation.optimize();
       std::cout << std::endl;
      }
     catch (GRBException e)
      {
       std::cout << "Gurobi error: " << e.getMessage() << "\n\n";
      }
     catch (...)
      {
       std::cout << "Error while attempting to optimize transform ... \n\n";
      }
    }
  }
solveTransform() [2/2]
void grbfrc::CharnesCooper::solveTransform (GRBCallback & callback)
transform()
void grbfrc::CharnesCooper::transform ()
Definition at line 25 of file CharnesCooper.cpp.
References grbfrc::_Algorithm::base_model, grbfrc::FMILPObj::denominator, getIndex(), grbfrc::FMILPObj::numerator, grbfrc::_Algorithm::objective, grbfrc::FMILPObj::sense, t, transformation, grbfrc::_Algorithm::vars, and y.
Referenced by getTransform(), and run().
  {
   // create t variable corr. to t = 1/(ex + f) // set objective to max {cy + dt} //
   t = transformation.addVar(0.0, GRB_INFINITY, 0.0, GRB_CONTINUOUS, "t");
   // create y variables corr. to y = tx //
   for (auto var : *vars) {
         y.push_back( new GRBVar( transformation.addVar(-GRB_INFINITY, GRB_INFINITY, 0.0, GRB_CONTINUOUS) ) );
         transformation.update();
         double lb { var->get(GRB_DoubleAttr_LB) };
         double ub { var->get(GRB_DoubleAttr_UB) };
         transformation.addConstr(*(y.back()) - lb*t >= 0.0);
         transformation.addConstr(*(y.back()) - ub*t <= 0.0);
   }
   transformation.update();
   // objective of the FLP: max (cx + d)/(ex + f) //
   GRBLinExpr& objNumerator = objective->numerator;
   double d { objNumerator.getConstant() };
   GRBLinExpr& objDenominator = objective->denominator;
   double f { objDenominator.getConstant() };
   int objSense = objective->sense;
   // set objective of transform to cy + dt
   GRBLinExpr transformObj { d * t };
   for (unsigned int i = 0; i < objNumerator.size(); i++)
    {
     GRBVar var = objNumerator.getVar(i);
     int j = getIndex(var);
     double coeff = objNumerator.getCoeff(i);
     transformObj += coeff * ( *y[j] );
    }
   transformation.setObjective(transformObj, objSense);
   // add ey + ft == 1 constraint //
   GRBLinExpr lhs { f * t };
   for (unsigned int i = 0; i < objDenominator.size(); i++)
    {
     GRBVar var = objDenominator.getVar(i);
     int j = getIndex(var);
     double coeff = objDenominator.getCoeff(i);
     lhs += coeff * ( *y[j] );
    }
   transformation.addConstr(lhs, GRB_EQUAL, 1.0);
   // constraints of the FLP: Ax {<=,=,>=} b //
   GRBConstr* constrs { base_model->getConstrs() };
   int numConstrs { base_model->get(GRB_IntAttr_NumConstrs) };
   // add Ay - bt {<=,=,>=} 0 constraints //
   for (int i = 0; i < numConstrs; i++)
    {
     GRBLinExpr origLhs { base_model->getRow(*constrs) };
     double b { constrs->get(GRB_DoubleAttr_RHS) };
     lhs = - b * t ;
     for (unsigned int i = 0; i < origLhs.size(); i++)
      {
       GRBVar var = origLhs.getVar(i);
       int j = getIndex(var);
       double coeff = origLhs.getCoeff(i);
       lhs += coeff * ( *y[j] );
      }
     char constrSense { constrs->get(GRB_CharAttr_Sense) };
     transformation.addConstr(lhs, constrSense, 0.0);
     constrs++;
    }
   transformation.update();
  }
writeSolution()
void grbfrc::CharnesCooper::writeSolution (FMILPSol ** xsolution) override virtual
Implements grbfrc::_Algorithm.
Definition at line 124 of file CharnesCooper.cpp.
References solution.
Referenced by grbfrc::Solver::_solve(), and run().
  {
   if (*xsolution) **xsolution = solution;
   else if (!*xsolution) *xsolution = new FMILPSol(solution);
   else std::cout << "No solution avaiable!" << std::endl;
  }
Member Data Documentation
invalid
bool grbfrc::CharnesCooper::invalid private
Definition at line 55 of file CharnesCooper.hpp.
Referenced by getTransform(), and solveTransform().
solution
FMILPSol grbfrc::CharnesCooper::solution private
Definition at line 54 of file CharnesCooper.hpp.
Referenced by backTransformSolution(), getSolution(), and writeSolution().
t
GRBVar grbfrc::CharnesCooper::t private
Definition at line 58 of file CharnesCooper.hpp.
Referenced by backTransformSolution(), and transform().
transformation
GRBModel grbfrc::CharnesCooper::transformation private
Definition at line 57 of file CharnesCooper.hpp.
Referenced by backTransformSolution(), CharnesCooper(), getTransform(), solveTransform(), and transform().
transformed
bool grbfrc::CharnesCooper::transformed private
Definition at line 56 of file CharnesCooper.hpp.
Referenced by getTransform().
y
std::vector<GRBVar*> grbfrc::CharnesCooper::y private
Definition at line 59 of file CharnesCooper.hpp.
Referenced by backTransformSolution(), and transform().
The documentation for this class was generated from the following files:
/datadisk/bbubu/projects/libgrbfrc/src/CharnesCooper.hpp
/datadisk/bbubu/projects/libgrbfrc/src/CharnesCooper.cpp