grbfrc-0.1: grbfrc::YGGY Class Reference
grbfrc::YGGY Class Reference
#include <YGGY.hpp>
Public Member Functions
YGGY (GRBEnv *env)
void printInvalidity ()
template<typename T >
int transform (GrbfrcCallback< T > *cb)
void do_the_rest (double umax)
GRBModel getTransform ()
void solveTransform ()
template<typename T >
void run (GrbfrcCallback< T > *cb=nullptr)
virtual void writeSolution (FMILPSol **xsolution) override
Public Member Functions inherited from grbfrc::_Algorithm
void init (GRBModel *xbase_model, FMILPObj *xobjective, std::vector< GRBVar *> *xvars, std::vector< double > *xstart_solution)
Private Member Functions
void backTransformSolution ()
int getIndex (GRBVar &var)
void define_tx ()
void define_objective (GRBLinExpr &objNumerator, int objSense)
void define_constraints (GRBLinExpr &objDenominator)
bool getUmax (double &umax)
Private Attributes
FMILPSol solution
bool invalid { false }
bool transformed { false }
GRBModel transformation
GRBVar u
std::vector< GRBVar * > tx
Additional Inherited Members
Protected Attributes inherited from grbfrc::_Algorithm
GRBModel * base_model
FMILPObj * objective
std::vector< GRBVar * > * vars
std::vector< double > * start_solution
GRBCallback * callback
Detailed Description
Definition at line 94 of file YGGY.hpp.
Constructor & Destructor Documentation
YGGY()
grbfrc::YGGY::YGGY (GRBEnv * env)
Definition at line 44 of file YGGY.cpp.
 : transformation { GRBModel(*env) } { }
Member Function Documentation
backTransformSolution()
void grbfrc::YGGY::backTransformSolution () private
Definition at line 234 of file YGGY.cpp.
References grbfrc::_Algorithm::base_model, grbfrc::FMILPSol::objVal, solution, transformation, tx, u, and grbfrc::FMILPSol::varVals.
Referenced by run().
{
     int status { transformation.get(GRB_IntAttr_Status) };
     if (status == GRB_OPTIMAL || status == GRB_INTERRUPTED || status == GRB_TIME_LIMIT) {
       solution.objVal = transformation.get(GRB_DoubleAttr_ObjVal);
       double uval { u.get(GRB_DoubleAttr_X) };
       for (int i = 0; i < base_model->get(GRB_IntAttr_NumVars); i++) {
         double value { tx[i]->get(GRB_DoubleAttr_X) };
         if (tx[i]->get(GRB_CharAttr_VType) == 'C')
             solution.varVals.push_back( value / uval );
         else
             solution.varVals.push_back( value );
       }
     }
     else std::cout << "GRB_Status : " << transformation.get(GRB_IntAttr_Status) << std::endl;
 }
define_constraints()
void grbfrc::YGGY::define_constraints (GRBLinExpr & objDenominator) private
Definition at line 155 of file YGGY.cpp.
References grbfrc::_Algorithm::base_model, getIndex(), transformation, tx, and u.
Referenced by do_the_rest(), and run().
{
     double f { objDenominator.getConstant() };
     GRBQuadExpr lhs { f * u };
     for (unsigned int i = 0; i < objDenominator.size(); i++) {
       GRBVar var = objDenominator.getVar(i);
       int j = getIndex(var);
       double coeff = objDenominator.getCoeff(i);
       if (var.get(GRB_CharAttr_VType) == 'C')
           lhs += coeff * ( *tx[j] );
       else
           lhs += coeff * u * ( *tx[j] );
     }
     transformation.addQConstr(lhs, GRB_EQUAL, 1.0);
     GRBConstr* constrs { base_model->getConstrs() };
     int numConstrs { base_model->get(GRB_IntAttr_NumConstrs) };
     for (int k = 0; k < numConstrs; k++) {
       GRBLinExpr origLhs { base_model->getRow(*constrs) };
       double b { constrs->get(GRB_DoubleAttr_RHS) };
       lhs = - b * u ;
       for (unsigned int i = 0; i < origLhs.size(); i++) {
         GRBVar var = origLhs.getVar(i);
         int j = getIndex(var);
         double coeff = origLhs.getCoeff(i);
         if (var.get(GRB_CharAttr_VType) == 'C')
             lhs += coeff * ( *tx[j] );
         else
             lhs += coeff * u * ( *tx[j] );
        }
       char constrSense { constrs->get(GRB_CharAttr_Sense) };
       transformation.addQConstr(lhs, constrSense, 0.0);
       constrs++;
      }
     transformation.update();
 }
define_objective()
void grbfrc::YGGY::define_objective (GRBLinExpr & objNumerator, int objSense) private
Definition at line 140 of file YGGY.cpp.
References getIndex(), transformation, tx, and u.
Referenced by do_the_rest(), and run().
{
     double d { objNumerator.getConstant() };
     GRBQuadExpr transformed_objective { d*u };
     for (unsigned int i = 0; i < objNumerator.size(); i++) {
       GRBVar var = objNumerator.getVar(i);
       int j = getIndex(var);
       double coeff = objNumerator.getCoeff(i);
       if (var.get(GRB_CharAttr_VType) == 'C')
           transformed_objective += coeff * ( *tx[j] );
       else
           transformed_objective += coeff * u * ( *tx[j] );
      }
     transformation.setObjective(transformed_objective, objSense);
 }
define_tx()
void grbfrc::YGGY::define_tx () private
Definition at line 104 of file YGGY.cpp.
References grbfrc::_Algorithm::start_solution, transformation, tx, u, and grbfrc::_Algorithm::vars.
Referenced by run(), and transform().
                      {
     int vindex { 0 };
     for (auto var: *vars) {
         double lb { var->get(GRB_DoubleAttr_LB) };
         double ub { var->get(GRB_DoubleAttr_UB) };
         if (var->get(GRB_CharAttr_VType) == 'C') {
             tx.push_back( new GRBVar( transformation.addVar(-GRB_INFINITY, GRB_INFINITY, 0.0, GRB_CONTINUOUS) ) );
             transformation.update();
             if (lb != -GRB_INFINITY)
                 transformation.addConstr(*(tx.back()) - lb*u >= 0.0);  // get umin & use ?!
             if (ub != GRB_INFINITY)
                 transformation.addConstr(*(tx.back()) - ub*u <= 0.0);  // use umax ?!
             // set start solution ... z_start = u_start * var_start
         }
         else {
             tx.push_back( new GRBVar( transformation.addVar(lb, ub, 0.0, GRB_BINARY) ) );
             if (start_solution) {
                 tx.back()->set(GRB_DoubleAttr_Start, (*start_solution)[vindex]);
             }
         }
         vindex++;
     }
 }
do_the_rest()
void grbfrc::YGGY::do_the_rest (double umax)
Definition at line 128 of file YGGY.cpp.
References define_constraints(), define_objective(), grbfrc::FMILPObj::denominator, grbfrc::Gloverizer::gloverize(), grbfrc::FMILPObj::numerator, grbfrc::_Algorithm::objective, grbfrc::FMILPObj::sense, transformation, and u.
Referenced by transform().
{
     std::cout << "Transform objective ..." << std::endl;
     define_objective(objective->numerator, objective->sense);
     std::cout << "Transform constraints ... " << std::endl;
     define_constraints(objective->denominator);
     transformation.update();
     std::cout << "Gloverize..." << std::endl;
     Gloverizer gloverizer(&transformation, &u, umax);
     gloverizer.gloverize();
     std::cout << "Done with transforming..." << std::endl;
 }
getIndex()
int grbfrc::YGGY::getIndex (GRBVar & var) private
Definition at line 250 of file YGGY.cpp.
References grbfrc::_Algorithm::base_model, and grbfrc::_Algorithm::vars.
Referenced by define_constraints(), define_objective(), and run().
{
     for (int i = 0; i < base_model->get(GRB_IntAttr_NumVars); i++)
         if (var.sameAs(*((*vars)[i]))) return i;
     return -1;
 }
getTransform()
GRBModel grbfrc::YGGY::getTransform ()
Definition at line 192 of file YGGY.cpp.
References invalid, printInvalidity(), transformation, and transformed.
Referenced by transform().
{
     if (invalid) {
         printInvalidity();
         return transformation;
     }
     else if (transformed)
         return transformation;
     else {
         //transform();
         return transformation;
     }
 }
getUmax()
bool grbfrc::YGGY::getUmax (double & umax) private
Definition at line 94 of file YGGY.cpp.
References grbfrc::_Algorithm::base_model, grbfrc::FMILPObj::denominator, and grbfrc::_Algorithm::objective.
Referenced by run(), and transform().
{
     std::cout << "Calculating Umax ...\n " << std::endl;    // if verbose ...
     base_model->setObjective(objective->denominator, GRB_MINIMIZE);
     base_model->optimize();
     std::cout << "\nDone calculating Umax.\n" << std::endl;       // if verbose ...
     if (base_model->get(GRB_IntAttr_Status) != GRB_OPTIMAL) return false;
     umax = 1 / base_model->get(GRB_DoubleAttr_ObjVal);
     return true;
 }
printInvalidity()
void grbfrc::YGGY::printInvalidity ()
Definition at line 46 of file YGGY.cpp.
Referenced by getTransform(), run(), and solveTransform().
{
    std::cout << "\n!!! === this->printInvalidity() doesn't make sense' === !!!\n\n";
 }
run()
template<typename T > void grbfrc::YGGY::run (GrbfrcCallback< T > * cb = nullptr) inline
Definition at line 142 of file YGGY.hpp.
References backTransformSolution(), define_constraints(), define_objective(), define_tx(), getIndex(), getUmax(), invalid, printInvalidity(), solveTransform(), transform(), transformed, and writeSolution().
Referenced by grbfrc::Solver::_solve().
{
           if (invalid)
               printInvalidity();
           else {
               std::cout << "\n=========== solving FMIP via YGGY transform ===========\n\n";
               if (!transformed) transform(cb);
               solveTransform();
               backTransformSolution();
           }
       }
solveTransform()
void grbfrc::YGGY::solveTransform ()
Definition at line 205 of file YGGY.cpp.
References invalid, printInvalidity(), and transformation.
Referenced by run(), and transform().
{
     if (invalid)
         printInvalidity();
     else {
         try {
             transformation.optimize();
             std::cout << std::endl;
         }
         catch (GRBException e) {
             std::cout << "Gurobi error: " << e.getMessage() << "\n\n";
         }
         catch (...) {
             std::cout << "Error while attempting to optimize transform ... \n\n";
         }
     }
 }
transform()
template<typename T > int grbfrc::YGGY::transform (GrbfrcCallback< T > * cb) inline
Definition at line 114 of file YGGY.hpp.
References grbfrc::_Algorithm::base_model, grbfrc::_Algorithm::callback, define_tx(), do_the_rest(), getTransform(), getUmax(), solveTransform(), grbfrc::_Algorithm::vars, and grbfrc::GrbfrcCallback< T >::yield().
Referenced by run().
{
           // denominator variable u = 1 / (dx + ey + f)
           double umax = 0.0;
           if (!getUmax(umax)) return 127;
           u = transformation.addVar(0.0, umax, 0.0, GRB_CONTINUOUS);
           // tx ~ (u*xc, xd)
           std::cout << "Define tx ..." << std::endl;
           define_tx();
           std::cout << "Setting Callback ..." << std::endl;
           if (cb) {
               callback = cb->yield(tx, vars);
               transformation.setCallback(callback);
           }
           // handle more generically
           transformation.set(GRB_IntParam_LazyConstraints, base_model->get(GRB_IntParam_LazyConstraints));
           transformation.update();
           do_the_rest(umax);
           return 0;
       }
writeSolution()
void grbfrc::YGGY::writeSolution (FMILPSol ** xsolution) override virtual
Implements grbfrc::_Algorithm.
Definition at line 222 of file YGGY.cpp.
References solution.
Referenced by grbfrc::Solver::_solve(), and run().
{
     if (*xsolution) **xsolution = solution;
     else if (!*xsolution) *xsolution = new FMILPSol(solution);
     else std::cout << "No solution avaiable!" << std::endl;
 }
Member Data Documentation
invalid
bool grbfrc::YGGY::invalid { false } private
Definition at line 100 of file YGGY.hpp.
Referenced by getTransform(), run(), and solveTransform().
solution
FMILPSol grbfrc::YGGY::solution private
Definition at line 98 of file YGGY.hpp.
Referenced by backTransformSolution(), and writeSolution().
transformation
GRBModel grbfrc::YGGY::transformation private
Definition at line 103 of file YGGY.hpp.
Referenced by backTransformSolution(), define_constraints(), define_objective(), define_tx(), do_the_rest(), getTransform(), and solveTransform().
transformed
bool grbfrc::YGGY::transformed { false } private
Definition at line 101 of file YGGY.hpp.
Referenced by getTransform(), and run().
tx
std::vector<GRBVar*> grbfrc::YGGY::tx private
Definition at line 105 of file YGGY.hpp.
Referenced by backTransformSolution(), define_constraints(), define_objective(), and define_tx().
u
GRBVar grbfrc::YGGY::u private
Definition at line 104 of file YGGY.hpp.
Referenced by backTransformSolution(), define_constraints(), define_objective(), define_tx(), and do_the_rest().
The documentation for this class was generated from the following files:
/datadisk/bbubu/projects/libgrbfrc/src/YGGY.hpp
/datadisk/bbubu/projects/libgrbfrc/src/YGGY.cpp